spring:
    application:
        name: cart-service
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: purely_cart_service
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 9060
    address: 0.0.0.0

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost